### ISSUE TITLE
host reference should be stun_host

### ISSUE THREAD

**Issue by joobcode** [jtriley/pystun#1]
180, 198, 206 "host" should be "stun_host" ?

Changing seemed to fix for me

**Comment by jtriley** [comment]
@joobcode Good call thanks for reporting. I'll try to fix and release soon.

**Comment by masari** [comment]
had to do these changes to make pystun work out of the box:

https://github.com/masari/pystun/commit/449d9ca4c253b6e9c2712cffb0f30e485852970c
