### ISSUE TITLE
Question about STUN server

### ISSUE THREAD

**Issue by kalasoo** [jtriley/pystun#3]
I'm an undergraduate student working on NAT traversal problem by making use of STUN and TURN. Thanks a lot for your implementation of this STUN client.
What I want to know is that is there any implementations of STUN server in Python? Or any other implementations that work well with your version of STUN client? 
PS: I found some samples written in Node.js (from github) and C/C++ (from other references).

**Comment by jtriley** [comment]
My apologies for not getting back to you sooner. To be honest I'm not a STUN expert at all. I just happened to need this module, saw that one existed (thanks to original author gaohawk), and noticed it wasn't available on PyPI so I decided to fix that situation. Nevertheless, doing some quick web searches for a STUN server in Python didn't return much, however, this looks sort of promising:

https://github.com/myrual/python-stun/blob/master/htcp/p2pnetwork/stun/stun.py#L195

I'm not sure if it even runs let alone works correctly so you'll have to do your own investigation but it's likely a good place to start. I'm going to close this now given that it's out of scope for pystun the stun client.
